baseURL = 'https://hachidaime.github.io'
languageCode = 'en-us'
title = 'Hachidaime'

theme = 'hugo-book'
enableEmoji = true

[params]
  BookTheme = 'dark'
  BookToC = true
  BookLogo = 'logo.png'
  BookSection = 'docs'
  BookRepo = 'https://github.com/alex-shpak/hugo-book'
  BookDateFormat = '2 January 2006'
  BookSearch = true
