baseURL = 'https://hachidaime.github.io'
languageCode = 'en-us'
title = 'Hachidaime'

theme = 'hugo-book'
enableEmoji = true
summaryLength = 20

[params]
  BookTheme = 'dark'
  BookToC = true
  BookLogo = 'logo.png'
  BookSection = 'docs'
  BookDateFormat = 'Monday, 2 January 2006'
  BookRepo = 'https://github.com/alex-shpak/hugo-book'
  BookSearch = true

[markup]
  [markup.highlight]
    style = 'dracula'
